#### 1. 划分数据集

In [70]:
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split  
import pandas as pd
#分块处理大文件
# chunk_iter = pd.read_csv("data/train_data.csv", chunksize=10000)
# chunks = [chunk for chunk in chunk_iter]
# train_data = pd.concat(chunks)
train_data = pd.read_csv("train/train.csv")
test_data = pd.read_csv("testaa/testaa.csv")
'''
train_data = train_data.drop(columns='issueDate')
test_data = test_data.drop(columns='issueDate')
'''
'''#截取前10000行数据
train_data=train_data.iloc[:10000,2:] '''
'''
# 划分特征变量与目标变量
X=train_data.drop(columns='isDefault')
Y=train_data['isDefault']
# 划分训练及测试集
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=0)
'''

train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53480 entries, 0 to 53479
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                53480 non-null  int64
 1   title             53480 non-null  int64
 2   career            50872 non-null  float64
 3   zip_code          53480 non-null  int64
 4   residence         53480 non-null  int64
 5   loan              53480 non-null  int64
 6   term              53480 non-null  int64
 7   interest_rate     53480 non-null  float64
 8   issue_time        53480 non-null  int64
 9   syndicated        53480 non-null  int64
 10  installment       53480 non-null  int64
 11  record_time       53480 non-null  int64
 12  history_time      53480 non-null  int64
 13  total_accounts    53480 non-null  float64
 14  balance_accounts  53480 non-null  float64
 15  balance_limit     53350 non-null  float64
 16  balance           53480 non-null  float64
 17  level             53480 non-null  object
 18  label             53480 non-null  int64
dtypes: float64(6), int64(12), object(1)
memory usage: 7.8+ MB

In [71]:
###   特征工程
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

# 1. 删除id列（正确用法）
train_data.drop('id', axis=1, inplace=True)  # 不赋值，直接修改原对象
# 删除zip-code
train_data.drop('zip_code',axis=1, inplace=True)
test_data.drop('zip_code',axis=1, inplace=True)

# 2. 分离特征类型
# 1. 初始自动分离（基于数据类型）
numerical_fea = train_data.select_dtypes(exclude=['object']).columns.tolist()
category_fea = train_data.select_dtypes(include=['object']).columns.tolist()
numerical_fea.remove('label')  # 移除标签列

# 2. 手动调整特定字段类型
features_to_convert = ['title', 'career','residence','term', 'syndicated', 'installment']  # 需重分类的特征

# 将指定特征从类别型移至数值型
for feature in features_to_convert:
        category_fea.append(feature)
        numerical_fea.remove(feature)

# 3. 缺失值处理
# 数值特征：中位数填充 balance_limit
train_data[numerical_fea] = train_data[numerical_fea].fillna(train_data[numerical_fea].median())
test_data[numerical_fea] = test_data[numerical_fea].fillna(test_data[numerical_fea].median())
# 类别特征：众数填充/-1填充 career
train_data[category_fea] = train_data[category_fea].fillna(-1)
test_data[category_fea] = test_data[category_fea].fillna(-1)
'''
imputer = SimpleImputer(strategy='most_frequent')
train_data[category_fea] = imputer.fit_transform(train_data[category_fea])
test_data[category_fea] = imputer.fit_transform(test_data[category_fea])
'''

# 4. 类别特征编码
def level_to_num(level):
    grade_map = {'A':0, 'B':1, 'C':2, 'D':3, 'E':4}
    grade = level[0]              # A/B/C/D/E
    sub = int(level[1])           # 0-5
    return grade_map[grade] * 6 + sub
train_data['level_num'] = train_data['level'].apply(level_to_num)
test_data['level_num'] = test_data['level'].apply(level_to_num)
train_data.drop('level', axis=1, inplace=True)
test_data.drop('level', axis=1, inplace=True)
numerical_fea.append('level_num')
category_fea.remove('level')
#新特征
train_data['utilization_ratio'] = train_data['balance'] / (train_data['balance_limit'] + 1e-6)  # 避免除0
train_data['active_account_ratio'] = train_data['balance_accounts'] / (train_data['total_accounts'] + 1e-6)  # 避免除0
train_data['available_credit'] = train_data['balance_limit'] - train_data['balance']
test_data['utilization_ratio'] = test_data['balance'] / (test_data['balance_limit'] + 1e-6)  # 避免除0
test_data['active_account_ratio'] = test_data['balance_accounts'] / (test_data['total_accounts'] + 1e-6)  # 避免除0
test_data['available_credit'] = test_data['balance_limit'] - test_data['balance']
'''
# 5. 数值特征标准化
scaler = StandardScaler()
train_data[numerical_fea] = scaler.fit_transform(train_data[numerical_fea])
'''

'\n# 5. 数值特征标准化\nscaler = StandardScaler()\ntrain_data[numerical_fea] = scaler.fit_transform(train_data[numerical_fea])\n'

In [72]:
# 对时间进行处理
import datetime
current_time = datetime.datetime.now()  # 或定义一个基准时间
original_time = ['issue_time', 'record_time', 'history_time']
for time_col in original_time:
    train_data[time_col + '_dt'] = pd.to_datetime(train_data[time_col], unit='s')  # Unix秒时间戳
    test_data[time_col + '_dt'] = pd.to_datetime(test_data[time_col], unit='s')
    train_data[time_col + '_age_days'] = (current_time - train_data[time_col + '_dt']).dt.days
    test_data[time_col + '_age_days'] = (current_time - test_data[time_col + '_dt']).dt.days
    numerical_fea.remove(time_col)
    numerical_fea.append(time_col + '_age_days')
    train_data.drop(time_col + '_dt',axis=1, inplace=True)
    test_data.drop(time_col + '_dt',axis=1, inplace=True)


train_data.drop(original_time,axis=1, inplace=True)
test_data.drop(original_time,axis=1, inplace=True)

In [64]:
category_fea

['title', 'career', 'residence', 'term', 'syndicated', 'installment']

In [65]:
numerical_fea

['loan',
 'interest_rate',
 'total_accounts',
 'balance_accounts',
 'balance_limit',
 'balance',
 'level_num',
 'issue_time_age_days',
 'record_time_age_days',
 'history_time_age_days']

In [11]:
train_data.head()

,title,career,residence,loan,term,interest_rate,syndicated,installment,total_accounts,balance_accounts,balance_limit,balance,label,level_num,utilization_ratio,active_account_ratio,available_credit,issue_time_age_days,record_time_age_days,history_time_age_days
0,9,0.0,1,7200,36,10.95,0,1,17.0,9.0,36200.0,13856.0,0,4,0.382762,0.529412,22344.0,5991,5991,14864
1,8,10.0,0,21300,36,12.95,0,0,17.0,9.0,20400.0,13773.0,1,6,0.675147,0.529412,6627.0,7269,6879,11487
2,8,7.0,1,10400,60,21.05,0,0,17.0,9.0,10800.0,2023.0,0,10,0.187315,0.529412,8777.0,5869,4309,11911
3,7,2.0,0,33050,36,16.40,0,1,17.0,9.0,24700.0,21992.0,0,9,0.890364,0.529412,2708.0,6752,6272,12368
4,8,3.0,1,5200,36,14.35,0,0,17.0,9.0,5100.0,1669.0,1,8,0.327255,0.529412,3431.0,6752,5972,16600

In [73]:
from sklearn.model_selection import train_test_split
 
feature_list = [col for col in train_data.columns if col != "label"]
for fea in numerical_fea:
    train_data[fea] = train_data[fea].astype('int64')
    test_data[fea] = test_data[fea].astype('int64')
train_data['career']  = train_data['career'].astype('int64')
test_data['career']  = test_data['career'].astype('int64')
X_train, X_validation, y_train, y_validation = train_test_split(train_data.loc[:, feature_list], train_data.loc[:, 'label'], test_size=0.2 , random_state=2000)

In [74]:
X_train.head()

,title,career,residence,loan,term,interest_rate,syndicated,installment,total_accounts,balance_accounts,balance_limit,balance,level_num,utilization_ratio,active_account_ratio,available_credit,issue_time_age_days,record_time_age_days,history_time_age_days
12232,7,10,0,5200,36,9,0,1,41,15,29800,13698,3,0.459664,0.365854,16102.0,6721,6721,11456
12974,6,-1,0,33050,36,19,0,0,15,8,53600,45655,10,0.851772,0.533333,7945.0,6691,6691,15412
47946,1,4,1,11000,12,30,0,0,10,6,6878,3776,3,0.548997,0.600000,3102.0,6824,7250,8421
6185,9,7,1,15350,36,13,0,0,43,17,15200,8884,7,0.584474,0.395349,6316.0,6022,5512,11334
29067,0,4,2,9000,12,10,0,0,5,2,1904,1546,6,0.811975,0.400000,358.0,6883,7084,8206

In [75]:
# 3. 模型建立与训练
# 确保 Notebook 内联显示图形
%matplotlib inline 
from catboost import CatBoostClassifier

model = CatBoostClassifier(iterations=2000,
                           task_type='GPU',
                           cat_features=category_fea,
                           eval_metric='AUC',
                           logging_level='Verbose',
                           learning_rate=0.05,
                           depth=6, 
                           l2_leaf_reg=5,
                           loss_function='Logloss',
                            early_stopping_rounds=300,
                           scale_pos_weight=(len(y_train[y_train==0])/len(y_train[y_train == 1])))
'''
model = CatBoostClassifier(iterations=5000,
                           cat_features=feature_list,
                           eval_metric='AUC',
                           logging_level='Verbose',
                           learning_rate=0.01,
                           depth=6, l2_leaf_reg=5,
                           loss_function='CrossEntropy')
                           '''
model.fit(X_train.loc[:, feature_list], y_train, 
          eval_set=(X_validation.loc[:, feature_list], y_validation), plot=True)

plt.show()

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Default metric period is 5 because AUC is/are not implemented for GPU

0:	test: 0.6266319	best: 0.6266319 (0)	total: 39.2ms	remaining: 1m 18s
1:	total: 76.2ms	remaining: 1m 16s
2:	total: 114ms	remaining: 1m 15s
3:	total: 152ms	remaining: 1m 15s
4:	total: 193ms	remaining: 1m 17s
5:	test: 0.6368431	best: 0.6368431 (5)	total: 231ms	remaining: 1m 16s
6:	total: 276ms	remaining: 1m 18s
7:	total: 316ms	remaining: 1m 18s
8:	total: 359ms	remaining: 1m 19s
9:	total: 396ms	remaining: 1m 18s
10:	test: 0.6360507	best: 0.6370536 (7)	total: 433ms	remaining: 1m 18s
11:	total: 473ms	remaining: 1m 18s
12:	total: 515ms	remaining: 1m 18s
13:	total: 563ms	remaining: 1m 19s
14:	total: 601ms	remaining: 1m 19s
15:	test: 0.6340558	best: 0.6370536 (7)	total: 639ms	remaining: 1m 19s
16:	total: 677ms	remaining: 1m 18s
17:	total: 715ms	remaining: 1m 18s
18:	total: 753ms	remaining: 1m 18s
19:	total: 793ms	remaining: 1m 18s
20:	test: 0.6360210	best: 0.6370536 (7)	total: 833ms	remaining: 1m 18s
21:	total: 870ms	remaining: 1m 18s
22:	total: 907ms	remaining: 1m 17s
23:	total: 945ms	remaining: 1m 17s
24:	total: 981ms	remaining: 1m 17s
25:	test: 0.6369814	best: 0.6372048 (24)	total: 1.02s	remaining: 1m 17s
26:	total: 1.06s	remaining: 1m 17s
27:	total: 1.1s	remaining: 1m 17s
28:	total: 1.15s	remaining: 1m 17s
29:	total: 1.18s	remaining: 1m 17s
30:	test: 0.6369333	best: 0.6372048 (24)	total: 1.23s	remaining: 1m 17s
31:	total: 1.26s	remaining: 1m 17s
32:	total: 1.3s	remaining: 1m 17s
33:	total: 1.35s	remaining: 1m 18s
34:	total: 1.39s	remaining: 1m 18s
35:	test: 0.6383969	best: 0.6383969 (35)	total: 1.43s	remaining: 1m 18s
36:	total: 1.47s	remaining: 1m 18s
37:	total: 1.51s	remaining: 1m 18s
38:	total: 1.56s	remaining: 1m 18s
39:	total: 1.59s	remaining: 1m 18s
40:	test: 0.6393191	best: 0.6394880 (39)	total: 1.63s	remaining: 1m 18s
41:	total: 1.67s	remaining: 1m 17s
42:	total: 1.71s	remaining: 1m 17s
43:	total: 1.75s	remaining: 1m 18s
44:	total: 1.8s	remaining: 1m 18s
45:	test: 0.6384410	best: 0.6394880 (39)	total: 1.84s	remaining: 1m 18s
46:	total: 1.88s	remaining: 1m 18s
47:	total: 1.93s	remaining: 1m 18s
48:	total: 1.96s	remaining: 1m 18s
49:	total: 2s	remaining: 1m 18s
50:	test: 0.6385178	best: 0.6394880 (39)	total: 2.04s	remaining: 1m 17s
51:	total: 2.08s	remaining: 1m 17s
52:	total: 2.12s	remaining: 1m 17s
53:	total: 2.15s	remaining: 1m 17s
54:	total: 2.19s	remaining: 1m 17s
55:	test: 0.6389118	best: 0.6394880 (39)	total: 2.23s	remaining: 1m 17s
56:	total: 2.26s	remaining: 1m 17s
57:	total: 2.3s	remaining: 1m 16s
58:	total: 2.34s	remaining: 1m 16s
59:	total: 2.38s	remaining: 1m 16s
60:	test: 0.6404082	best: 0.6404082 (60)	total: 2.42s	remaining: 1m 16s
61:	total: 2.45s	remaining: 1m 16s
62:	total: 2.5s	remaining: 1m 16s
63:	total: 2.54s	remaining: 1m 16s
64:	total: 2.58s	remaining: 1m 16s
65:	test: 0.6408712	best: 0.6408712 (65)	total: 2.62s	remaining: 1m 16s
66:	total: 2.66s	remaining: 1m 16s
67:	total: 2.7s	remaining: 1m 16s
68:	total: 2.73s	remaining: 1m 16s
69:	total: 2.77s	remaining: 1m 16s
70:	test: 0.6410980	best: 0.6410980 (70)	total: 2.81s	remaining: 1m 16s
71:	total: 2.85s	remaining: 1m 16s
72:	total: 2.88s	remaining: 1m 16s
73:	total: 2.92s	remaining: 1m 15s
74:	total: 2.96s	remaining: 1m 15s
75:	test: 0.6412323	best: 0.6414119 (73)	total: 3s	remaining: 1m 15s
76:	total: 3.04s	remaining: 1m 15s
77:	total: 3.07s	remaining: 1m 15s
78:	total: 3.11s	remaining: 1m 15s
79:	total: 3.15s	remaining: 1m 15s
80:	test: 0.6417488	best: 0.6417488 (80)	total: 3.18s	remaining: 1m 15s
81:	total: 3.21s	remaining: 1m 15s
82:	total: 3.25s	remaining: 1m 15s
83:	total: 3.29s	remaining: 1m 15s
84:	total: 3.33s	remaining: 1m 14s
85:	test: 0.6416707	best: 0.6417488 (80)	total: 3.35s	remaining: 1m 14s
86:	total: 3.39s	remaining: 1m 14s
87:	total: 3.42s	remaining: 1m 14s
88:	total: 3.46s	remaining: 1m 14s
89:	total: 3.5s	remaining: 1m 14s
90:	test: 0.6415813	best: 0.6417488 (80)	total: 3.54s	remaining: 1m 14s
91:	total: 3.56s	remaining: 1m 13s
92:	total: 3.6s	remaining: 1m 13s
93:	total: 3.64s	remaining: 1m 13s
94:	total: 3.68s	remaining: 1m 13s
95:	test: 0.6415481	best: 0.6417488 (80)	total: 3.72s	remaining: 1m 13s
96:	total: 3.76s	remaining: 1m 13s
97:	total: 3.8s	remaining: 1m 13s
98:	total: 3.83s	remaining: 1m 13s
99:	total: 3.87s	remaining: 1m 13s
100:	test: 0.6427661	best: 0.6428261 (98)	total: 3.91s	remaining: 1m 13s
101:	total: 3.95s	remaining: 1m 13s
102:	total: 4s	remaining: 1m 13s
103:	total: 4.04s	remaining: 1m 13s
104:	total: 4.07s	remaining: 1m 13s
105:	test: 0.6428135	best: 0.6429276 (101)	total: 4.11s	remaining: 1m 13s
106:	total: 4.15s	remaining: 1m 13s
107:	total: 4.18s	remaining: 1m 13s
108:	total: 4.22s	remaining: 1m 13s
109:	total: 4.26s	remaining: 1m 13s
110:	test: 0.6430621	best: 0.6431410 (108)	total: 4.3s	remaining: 1m 13s
111:	total: 4.34s	remaining: 1m 13s
112:	total: 4.38s	remaining: 1m 13s
113:	total: 4.42s	remaining: 1m 13s
114:	total: 4.45s	remaining: 1m 13s
115:	test: 0.6431910	best: 0.6432442 (112)	total: 4.49s	remaining: 1m 12s
116:	total: 4.53s	remaining: 1m 12s
117:	total: 4.57s	remaining: 1m 12s
118:	total: 4.61s	remaining: 1m 12s
119:	total: 4.64s	remaining: 1m 12s
120:	test: 0.6430176	best: 0.6432455 (117)	total: 4.67s	remaining: 1m 12s
121:	total: 4.71s	remaining: 1m 12s
122:	total: 4.75s	remaining: 1m 12s
123:	total: 4.79s	remaining: 1m 12s
124:	total: 4.82s	remaining: 1m 12s
125:	test: 0.6429086	best: 0.6432455 (117)	total: 4.87s	remaining: 1m 12s
126:	total: 4.91s	remaining: 1m 12s
127:	total: 4.94s	remaining: 1m 12s
128:	total: 4.97s	remaining: 1m 12s
129:	total: 5.01s	remaining: 1m 12s
130:	test: 0.6434506	best: 0.6434506 (129)	total: 5.04s	remaining: 1m 11s
131:	total: 5.08s	remaining: 1m 11s
132:	total: 5.12s	remaining: 1m 11s
133:	total: 5.16s	remaining: 1m 11s
134:	total: 5.19s	remaining: 1m 11s
135:	test: 0.6436176	best: 0.6436537 (133)	total: 5.23s	remaining: 1m 11s
136:	total: 5.26s	remaining: 1m 11s
137:	total: 5.3s	remaining: 1m 11s
138:	total: 5.33s	remaining: 1m 11s
139:	total: 5.37s	remaining: 1m 11s
140:	test: 0.6442785	best: 0.6442953 (138)	total: 5.41s	remaining: 1m 11s
141:	total: 5.44s	remaining: 1m 11s
142:	total: 5.48s	remaining: 1m 11s
143:	total: 5.52s	remaining: 1m 11s
144:	total: 5.57s	remaining: 1m 11s
145:	test: 0.6445217	best: 0.6445217 (145)	total: 5.61s	remaining: 1m 11s
146:	total: 5.65s	remaining: 1m 11s
147:	total: 5.69s	remaining: 1m 11s
148:	total: 5.73s	remaining: 1m 11s
149:	total: 5.77s	remaining: 1m 11s
150:	test: 0.6443614	best: 0.6445217 (145)	total: 5.8s	remaining: 1m 11s
151:	total: 5.84s	remaining: 1m 11s
152:	total: 5.88s	remaining: 1m 10s
153:	total: 5.92s	remaining: 1m 10s
154:	total: 5.95s	remaining: 1m 10s
155:	test: 0.6448995	best: 0.6449417 (151)	total: 5.99s	remaining: 1m 10s
156:	total: 6.03s	remaining: 1m 10s
157:	total: 6.07s	remaining: 1m 10s
158:	total: 6.11s	remaining: 1m 10s
159:	total: 6.14s	remaining: 1m 10s
160:	test: 0.6448088	best: 0.6449417 (151)	total: 6.18s	remaining: 1m 10s
161:	total: 6.22s	remaining: 1m 10s
162:	total: 6.26s	remaining: 1m 10s
163:	total: 6.3s	remaining: 1m 10s
164:	total: 6.34s	remaining: 1m 10s
165:	test: 0.6455135	best: 0.6455205 (163)	total: 6.38s	remaining: 1m 10s
166:	total: 6.42s	remaining: 1m 10s
167:	total: 6.46s	remaining: 1m 10s
168:	total: 6.5s	remaining: 1m 10s
169:	total: 6.54s	remaining: 1m 10s
170:	test: 0.6457066	best: 0.6457066 (170)	total: 6.57s	remaining: 1m 10s
171:	total: 6.62s	remaining: 1m 10s
172:	total: 6.66s	remaining: 1m 10s
173:	total: 6.7s	remaining: 1m 10s
174:	total: 6.73s	remaining: 1m 10s
175:	test: 0.6458529	best: 0.6458529 (175)	total: 6.78s	remaining: 1m 10s
176:	total: 6.81s	remaining: 1m 10s
177:	total: 6.85s	remaining: 1m 10s
178:	total: 6.89s	remaining: 1m 10s
179:	total: 6.92s	remaining: 1m 10s
180:	test: 0.6458316	best: 0.6458529 (175)	total: 6.97s	remaining: 1m 10s
181:	total: 7s	remaining: 1m 9s
182:	total: 7.04s	remaining: 1m 9s
183:	total: 7.08s	remaining: 1m 9s
184:	total: 7.12s	remaining: 1m 9s
185:	test: 0.6460443	best: 0.6460511 (181)	total: 7.15s	remaining: 1m 9s
186:	total: 7.19s	remaining: 1m 9s
187:	total: 7.22s	remaining: 1m 9s
188:	total: 7.26s	remaining: 1m 9s
189:	total: 7.3s	remaining: 1m 9s
190:	test: 0.6464362	best: 0.6464362 (190)	total: 7.34s	remaining: 1m 9s
191:	total: 7.37s	remaining: 1m 9s
192:	total: 7.41s	remaining: 1m 9s
193:	total: 7.44s	remaining: 1m 9s
194:	total: 7.48s	remaining: 1m 9s
195:	test: 0.6465023	best: 0.6465182 (191)	total: 7.51s	remaining: 1m 9s
196:	total: 7.55s	remaining: 1m 9s
197:	total: 7.59s	remaining: 1m 9s
198:	total: 7.64s	remaining: 1m 9s
199:	total: 7.68s	remaining: 1m 9s
200:	test: 0.6465935	best: 0.6466069 (198)	total: 7.72s	remaining: 1m 9s
201:	total: 7.76s	remaining: 1m 9s
202:	total: 7.8s	remaining: 1m 9s
203:	total: 7.84s	remaining: 1m 9s
204:	total: 7.88s	remaining: 1m 9s
205:	test: 0.6467991	best: 0.6468941 (204)	total: 7.92s	remaining: 1m 8s
206:	total: 7.96s	remaining: 1m 8s
207:	total: 7.99s	remaining: 1m 8s
208:	total: 8.03s	remaining: 1m 8s
209:	total: 8.06s	remaining: 1m 8s
210:	test: 0.6468433	best: 0.6468941 (204)	total: 8.09s	remaining: 1m 8s
211:	total: 8.12s	remaining: 1m 8s
212:	total: 8.16s	remaining: 1m 8s
213:	total: 8.2s	remaining: 1m 8s
214:	total: 8.23s	remaining: 1m 8s
215:	test: 0.6466641	best: 0.6468941 (204)	total: 8.27s	remaining: 1m 8s
216:	total: 8.31s	remaining: 1m 8s
217:	total: 8.36s	remaining: 1m 8s
218:	total: 8.39s	remaining: 1m 8s
219:	total: 8.43s	remaining: 1m 8s
220:	test: 0.6472288	best: 0.6473744 (217)	total: 8.47s	remaining: 1m 8s
221:	total: 8.52s	remaining: 1m 8s
222:	total: 8.56s	remaining: 1m 8s
223:	total: 8.6s	remaining: 1m 8s
224:	total: 8.63s	remaining: 1m 8s
225:	test: 0.6475533	best: 0.6475533 (225)	total: 8.67s	remaining: 1m 8s
226:	total: 8.7s	remaining: 1m 7s
227:	total: 8.74s	remaining: 1m 7s
228:	total: 8.79s	remaining: 1m 8s
229:	total: 8.83s	remaining: 1m 7s
230:	test: 0.6477804	best: 0.6477804 (230)	total: 8.87s	remaining: 1m 7s
231:	total: 8.91s	remaining: 1m 7s
232:	total: 8.96s	remaining: 1m 7s
233:	total: 8.99s	remaining: 1m 7s
234:	total: 9.03s	remaining: 1m 7s
235:	test: 0.6479102	best: 0.6479102 (235)	total: 9.07s	remaining: 1m 7s
236:	total: 9.11s	remaining: 1m 7s
237:	total: 9.15s	remaining: 1m 7s
238:	total: 9.19s	remaining: 1m 7s
239:	total: 9.23s	remaining: 1m 7s
240:	test: 0.6482986	best: 0.6482990 (237)	total: 9.26s	remaining: 1m 7s
241:	total: 9.3s	remaining: 1m 7s
242:	total: 9.34s	remaining: 1m 7s
243:	total: 9.38s	remaining: 1m 7s
244:	total: 9.42s	remaining: 1m 7s
245:	test: 0.6484758	best: 0.6484898 (243)	total: 9.46s	remaining: 1m 7s
246:	total: 9.5s	remaining: 1m 7s
247:	total: 9.54s	remaining: 1m 7s
248:	total: 9.57s	remaining: 1m 7s
249:	total: 9.61s	remaining: 1m 7s
250:	test: 0.6488835	best: 0.6488883 (247)	total: 9.65s	remaining: 1m 7s
251:	total: 9.69s	remaining: 1m 7s
252:	total: 9.73s	remaining: 1m 7s
253:	total: 9.77s	remaining: 1m 7s
254:	total: 9.8s	remaining: 1m 7s
255:	test: 0.6488855	best: 0.6488889 (252)	total: 9.83s	remaining: 1m 7s
256:	total: 9.87s	remaining: 1m 6s
257:	total: 9.91s	remaining: 1m 6s
258:	total: 9.95s	remaining: 1m 6s
259:	total: 9.98s	remaining: 1m 6s
260:	test: 0.6490569	best: 0.6490698 (257)	total: 10s	remaining: 1m 6s
261:	total: 10.1s	remaining: 1m 6s
262:	total: 10.1s	remaining: 1m 6s
263:	total: 10.1s	remaining: 1m 6s
264:	total: 10.2s	remaining: 1m 6s
265:	test: 0.6489934	best: 0.6490698 (257)	total: 10.2s	remaining: 1m 6s
266:	total: 10.3s	remaining: 1m 6s
267:	total: 10.3s	remaining: 1m 6s
268:	total: 10.3s	remaining: 1m 6s
269:	total: 10.4s	remaining: 1m 6s
270:	test: 0.6490011	best: 0.6490698 (257)	total: 10.4s	remaining: 1m 6s
271:	total: 10.5s	remaining: 1m 6s
272:	total: 10.5s	remaining: 1m 6s
273:	total: 10.5s	remaining: 1m 6s
274:	total: 10.6s	remaining: 1m 6s
275:	test: 0.6490759	best: 0.6493692 (271)	total: 10.6s	remaining: 1m 6s
276:	total: 10.6s	remaining: 1m 6s
277:	total: 10.7s	remaining: 1m 6s
278:	total: 10.7s	remaining: 1m 6s
279:	total: 10.8s	remaining: 1m 6s
280:	test: 0.6494060	best: 0.6494359 (278)	total: 10.8s	remaining: 1m 6s
281:	total: 10.8s	remaining: 1m 5s
282:	total: 10.9s	remaining: 1m 5s
283:	total: 10.9s	remaining: 1m 5s
284:	total: 10.9s	remaining: 1m 5s
285:	test: 0.6494550	best: 0.6494550 (283)	total: 11s	remaining: 1m 5s
286:	total: 11s	remaining: 1m 5s
287:	total: 11.1s	remaining: 1m 5s
288:	total: 11.1s	remaining: 1m 5s
289:	total: 11.1s	remaining: 1m 5s
290:	test: 0.6498331	best: 0.6498331 (290)	total: 11.2s	remaining: 1m 5s
291:	total: 11.2s	remaining: 1m 5s
292:	total: 11.3s	remaining: 1m 5s
293:	total: 11.3s	remaining: 1m 5s
294:	total: 11.3s	remaining: 1m 5s
295:	test: 0.6499653	best: 0.6499653 (295)	total: 11.4s	remaining: 1m 5s
296:	total: 11.4s	remaining: 1m 5s
297:	total: 11.5s	remaining: 1m 5s
298:	total: 11.5s	remaining: 1m 5s
299:	total: 11.5s	remaining: 1m 5s
300:	test: 0.6497902	best: 0.6499712 (297)	total: 11.6s	remaining: 1m 5s
301:	total: 11.6s	remaining: 1m 5s
302:	total: 11.6s	remaining: 1m 5s
303:	total: 11.7s	remaining: 1m 5s
304:	total: 11.7s	remaining: 1m 5s
305:	test: 0.6499203	best: 0.6499712 (297)	total: 11.8s	remaining: 1m 5s
306:	total: 11.8s	remaining: 1m 4s
307:	total: 11.8s	remaining: 1m 4s
308:	total: 11.9s	remaining: 1m 4s
309:	total: 11.9s	remaining: 1m 4s
310:	test: 0.6498947	best: 0.6500018 (307)	total: 11.9s	remaining: 1m 4s
311:	total: 12s	remaining: 1m 4s
312:	total: 12s	remaining: 1m 4s
313:	total: 12.1s	remaining: 1m 4s
314:	total: 12.1s	remaining: 1m 4s
315:	test: 0.6499087	best: 0.6500018 (307)	total: 12.1s	remaining: 1m 4s
316:	total: 12.2s	remaining: 1m 4s
317:	total: 12.2s	remaining: 1m 4s
318:	total: 12.2s	remaining: 1m 4s
319:	total: 12.3s	remaining: 1m 4s
320:	test: 0.6498041	best: 0.6500018 (307)	total: 12.3s	remaining: 1m 4s
321:	total: 12.3s	remaining: 1m 4s
322:	total: 12.4s	remaining: 1m 4s
323:	total: 12.4s	remaining: 1m 4s
324:	total: 12.5s	remaining: 1m 4s
325:	test: 0.6497976	best: 0.6500018 (307)	total: 12.5s	remaining: 1m 4s
326:	total: 12.5s	remaining: 1m 4s
327:	total: 12.6s	remaining: 1m 4s
328:	total: 12.6s	remaining: 1m 3s
329:	total: 12.6s	remaining: 1m 3s
330:	test: 0.6497917	best: 0.6500018 (307)	total: 12.7s	remaining: 1m 3s
331:	total: 12.7s	remaining: 1m 3s
332:	total: 12.7s	remaining: 1m 3s
333:	total: 12.8s	remaining: 1m 3s
334:	total: 12.8s	remaining: 1m 3s
335:	test: 0.6497760	best: 0.6500018 (307)	total: 12.9s	remaining: 1m 3s
336:	total: 12.9s	remaining: 1m 3s
337:	total: 12.9s	remaining: 1m 3s
338:	total: 13s	remaining: 1m 3s
339:	total: 13s	remaining: 1m 3s
340:	test: 0.6498441	best: 0.6500018 (307)	total: 13.1s	remaining: 1m 3s
341:	total: 13.1s	remaining: 1m 3s
342:	total: 13.1s	remaining: 1m 3s
343:	total: 13.2s	remaining: 1m 3s
344:	total: 13.2s	remaining: 1m 3s
345:	test: 0.6499053	best: 0.6500018 (307)	total: 13.3s	remaining: 1m 3s
346:	total: 13.3s	remaining: 1m 3s
347:	total: 13.3s	remaining: 1m 3s
348:	total: 13.4s	remaining: 1m 3s
349:	total: 13.4s	remaining: 1m 3s
350:	test: 0.6499935	best: 0.6500018 (307)	total: 13.4s	remaining: 1m 3s
351:	total: 13.5s	remaining: 1m 3s
352:	total: 13.5s	remaining: 1m 3s
353:	total: 13.6s	remaining: 1m 3s
354:	total: 13.6s	remaining: 1m 2s
355:	test: 0.6501120	best: 0.6501124 (353)	total: 13.6s	remaining: 1m 2s
356:	total: 13.7s	remaining: 1m 2s
357:	total: 13.7s	remaining: 1m 2s
358:	total: 13.7s	remaining: 1m 2s
359:	total: 13.8s	remaining: 1m 2s
360:	test: 0.6503168	best: 0.6503168 (359)	total: 13.8s	remaining: 1m 2s
361:	total: 13.8s	remaining: 1m 2s
362:	total: 13.9s	remaining: 1m 2s
363:	total: 13.9s	remaining: 1m 2s
364:	total: 13.9s	remaining: 1m 2s
365:	test: 0.6504291	best: 0.6504299 (364)	total: 14s	remaining: 1m 2s
366:	total: 14s	remaining: 1m 2s
367:	total: 14s	remaining: 1m 2s
368:	total: 14.1s	remaining: 1m 2s
369:	total: 14.1s	remaining: 1m 2s
370:	test: 0.6505391	best: 0.6505391 (370)	total: 14.2s	remaining: 1m 2s
371:	total: 14.2s	remaining: 1m 2s
372:	total: 14.2s	remaining: 1m 2s
373:	total: 14.3s	remaining: 1m 2s
374:	total: 14.3s	remaining: 1m 1s
375:	test: 0.6505746	best: 0.6506079 (372)	total: 14.3s	remaining: 1m 1s
376:	total: 14.4s	remaining: 1m 1s
377:	total: 14.4s	remaining: 1m 1s
378:	total: 14.4s	remaining: 1m 1s
379:	total: 14.5s	remaining: 1m 1s
380:	test: 0.6505577	best: 0.6506079 (372)	total: 14.5s	remaining: 1m 1s
381:	total: 14.6s	remaining: 1m 1s
382:	total: 14.6s	remaining: 1m 1s
383:	total: 14.6s	remaining: 1m 1s
384:	total: 14.7s	remaining: 1m 1s
385:	test: 0.6505837	best: 0.6506079 (372)	total: 14.7s	remaining: 1m 1s
386:	total: 14.7s	remaining: 1m 1s
387:	total: 14.8s	remaining: 1m 1s
388:	total: 14.8s	remaining: 1m 1s
389:	total: 14.9s	remaining: 1m 1s
390:	test: 0.6508378	best: 0.6508378 (390)	total: 14.9s	remaining: 1m 1s
391:	total: 14.9s	remaining: 1m 1s
392:	total: 15s	remaining: 1m 1s
393:	total: 15s	remaining: 1m 1s
394:	total: 15s	remaining: 1m 1s
395:	test: 0.6509088	best: 0.6509088 (395)	total: 15.1s	remaining: 1m 1s
396:	total: 15.1s	remaining: 1m 1s
397:	total: 15.2s	remaining: 1m 1s
398:	total: 15.2s	remaining: 1m
399:	total: 15.2s	remaining: 1m
400:	test: 0.6509615	best: 0.6509859 (398)	total: 15.3s	remaining: 1m
401:	total: 15.3s	remaining: 1m
402:	total: 15.4s	remaining: 1m
403:	total: 15.4s	remaining: 1m
404:	total: 15.4s	remaining: 1m
405:	test: 0.6506202	best: 0.6509859 (398)	total: 15.5s	remaining: 1m
406:	total: 15.5s	remaining: 1m
407:	total: 15.5s	remaining: 1m
408:	total: 15.6s	remaining: 1m
409:	total: 15.6s	remaining: 1m
410:	test: 0.6506421	best: 0.6509859 (398)	total: 15.7s	remaining: 1m
411:	total: 15.7s	remaining: 1m
412:	total: 15.7s	remaining: 1m
413:	total: 15.8s	remaining: 1m
414:	total: 15.8s	remaining: 1m
415:	test: 0.6505309	best: 0.6509859 (398)	total: 15.8s	remaining: 1m
416:	total: 15.9s	remaining: 1m
417:	total: 15.9s	remaining: 1m
418:	total: 16s	remaining: 1m
419:	total: 16s	remaining: 1m
420:	test: 0.6505728	best: 0.6509859 (398)	total: 16s	remaining: 1m
421:	total: 16.1s	remaining: 1m
422:	total: 16.1s	remaining: 1m
423:	total: 16.2s	remaining: 1m
424:	total: 16.2s	remaining: 1m
425:	test: 0.6502947	best: 0.6509859 (398)	total: 16.2s	remaining: 60s
426:	total: 16.3s	remaining: 59.9s
427:	total: 16.3s	remaining: 59.9s
428:	total: 16.3s	remaining: 59.8s
429:	total: 16.4s	remaining: 59.8s
430:	test: 0.6501805	best: 0.6509859 (398)	total: 16.4s	remaining: 59.7s
431:	total: 16.5s	remaining: 59.7s
432:	total: 16.5s	remaining: 59.7s
433:	total: 16.5s	remaining: 59.7s
434:	total: 16.6s	remaining: 59.6s
435:	test: 0.6499569	best: 0.6509859 (398)	total: 16.6s	remaining: 59.6s
436:	total: 16.6s	remaining: 59.5s
437:	total: 16.7s	remaining: 59.5s
438:	total: 16.7s	remaining: 59.5s
439:	total: 16.8s	remaining: 59.4s
440:	test: 0.6499239	best: 0.6509859 (398)	total: 16.8s	remaining: 59.4s
441:	total: 16.8s	remaining: 59.3s
442:	total: 16.9s	remaining: 59.3s
443:	total: 16.9s	remaining: 59.3s
444:	total: 17s	remaining: 59.2s
445:	test: 0.6500656	best: 0.6509859 (398)	total: 17s	remaining: 59.2s
446:	total: 17s	remaining: 59.2s
447:	total: 17.1s	remaining: 59.1s
448:	total: 17.1s	remaining: 59.1s
449:	total: 17.1s	remaining: 59s
450:	test: 0.6499896	best: 0.6509859 (398)	total: 17.2s	remaining: 59s
451:	total: 17.2s	remaining: 58.9s
452:	total: 17.2s	remaining: 58.9s
453:	total: 17.3s	remaining: 58.8s
454:	total: 17.3s	remaining: 58.8s
455:	test: 0.6499405	best: 0.6509859 (398)	total: 17.3s	remaining: 58.7s
456:	total: 17.4s	remaining: 58.7s
457:	total: 17.4s	remaining: 58.7s
458:	total: 17.5s	remaining: 58.6s
459:	total: 17.5s	remaining: 58.6s
460:	test: 0.6498604	best: 0.6509859 (398)	total: 17.5s	remaining: 58.5s
461:	total: 17.6s	remaining: 58.5s
462:	total: 17.6s	remaining: 58.5s
463:	total: 17.7s	remaining: 58.5s
464:	total: 17.7s	remaining: 58.5s
465:	test: 0.6499201	best: 0.6509859 (398)	total: 17.8s	remaining: 58.5s
466:	total: 17.8s	remaining: 58.4s
467:	total: 17.8s	remaining: 58.4s
468:	total: 17.9s	remaining: 58.3s
469:	total: 17.9s	remaining: 58.3s
470:	test: 0.6499060	best: 0.6509859 (398)	total: 17.9s	remaining: 58.2s

In [118]:
# 4.测试集预测
preds = model.predict_proba(test_data[feature_list])
preds

array([[0.57207427, 0.42792573],
       [0.86148328, 0.13851672],
       [0.52009973, 0.47990027],
       ...,
       [0.46044245, 0.53955755],
       [0.44733027, 0.55266973],
       [0.38687271, 0.61312729]])

In [119]:
test_data['label'] = preds[:, 1]  # 取正类的概率存储
test_data[['id', 'label']].to_csv('submission.csv', index=False)

In [66]:
import catboost
from catboost import CatBoostClassifier
from catboost.utils import get_roc_curve
# 获取类别特征索引（假设X_train是DataFrame）
cat_features_idx = [i for i, col in enumerate(X_train.columns) 
                    if X_train[col].dtype == 'object']  
# 创建并训练一个CatBoost分类器
model = CatBoostClassifier(iterations=1000,
                           task_type='GPU',
                           cat_features=feature_list,
                           eval_metric='AUC',
                           logging_level='Verbose',
                           learning_rate=0.05,
                           depth=6, 
                           l2_leaf_reg=5,
                           loss_function='Logloss',
                            early_stopping_rounds=300,
                           scale_pos_weight=(len(y_train[y_train==0])/len(y_train[y_train == 1])))
model.fit(X_train, y_train)
# 假设 df 是你的 Pandas DataFrame
train_data = catboost.Pool(data=X_train, label=y_train)
# 获取特征重要性评估
feature_importance = model.get_feature_importance(data=train_data, type='LossFunctionChange')
# 获取特征名称
feature_names = train_data.get_feature_names()
# 将特征重要性和特征名称结合起来，创建一个字典
feature_importance_dict = dict(zip(feature_names, feature_importance))

# 将特征重要性排序
sorted_feature_importance = sorted(feature_importance_dict.items(), key=lambda x: x[1], reverse=True)

# 提取排序后的特征名称和重要性
sorted_feature_names, sorted_feature_importance = zip(*sorted_feature_importance)

plt.figure(figsize=(10, 6))
plt.barh(sorted_feature_names[:10], sorted_feature_importance[:10])
plt.xlabel('Feature Importance')
plt.title('Top 10 Important Features')
plt.gca().invert_yaxis()  # 反转y轴以显示重要性高的特征在顶部
plt.show()
# 打印特征重要性得分
for i, score in enumerate(feature_importance):
    print(f'Feature {i}: {score}')

Default metric period is 5 because AUC is/are not implemented for GPU

0:	total: 54ms	remaining: 53.9s
1:	total: 118ms	remaining: 58.8s
2:	total: 166ms	remaining: 55s
3:	total: 222ms	remaining: 55.4s
4:	total: 275ms	remaining: 54.7s
5:	total: 329ms	remaining: 54.6s
6:	total: 384ms	remaining: 54.5s
7:	total: 438ms	remaining: 54.3s
8:	total: 487ms	remaining: 53.6s
9:	total: 537ms	remaining: 53.1s
10:	total: 585ms	remaining: 52.6s
11:	total: 642ms	remaining: 52.9s
12:	total: 692ms	remaining: 52.5s
13:	total: 738ms	remaining: 52s
14:	total: 789ms	remaining: 51.8s
15:	total: 852ms	remaining: 52.4s
16:	total: 904ms	remaining: 52.3s
17:	total: 960ms	remaining: 52.4s
18:	total: 1.01s	remaining: 52.2s
19:	total: 1.07s	remaining: 52.6s
20:	total: 1.12s	remaining: 52.4s
21:	total: 1.17s	remaining: 52.1s
22:	total: 1.22s	remaining: 51.8s
23:	total: 1.27s	remaining: 51.5s
24:	total: 1.31s	remaining: 51.3s
25:	total: 1.36s	remaining: 51s
26:	total: 1.41s	remaining: 50.8s
27:	total: 1.46s	remaining: 50.6s
28:	total: 1.5s	remaining: 50.3s
29:	total: 1.55s	remaining: 50.1s
30:	total: 1.6s	remaining: 50s
31:	total: 1.65s	remaining: 49.9s
32:	total: 1.7s	remaining: 49.8s
33:	total: 1.75s	remaining: 49.7s
34:	total: 1.79s	remaining: 49.5s
35:	total: 1.84s	remaining: 49.3s
36:	total: 1.89s	remaining: 49.2s
37:	total: 1.94s	remaining: 49.1s
38:	total: 2s	remaining: 49.2s
39:	total: 2.04s	remaining: 49.1s
40:	total: 2.09s	remaining: 48.9s
41:	total: 2.14s	remaining: 48.8s
42:	total: 2.19s	remaining: 48.8s
43:	total: 2.23s	remaining: 48.6s
44:	total: 2.28s	remaining: 48.5s
45:	total: 2.33s	remaining: 48.4s
46:	total: 2.38s	remaining: 48.3s
47:	total: 2.43s	remaining: 48.2s
48:	total: 2.48s	remaining: 48s
49:	total: 2.53s	remaining: 48.1s
50:	total: 2.58s	remaining: 48.1s
51:	total: 2.63s	remaining: 48s
52:	total: 2.69s	remaining: 48s
53:	total: 2.75s	remaining: 48.1s
54:	total: 2.79s	remaining: 48s
55:	total: 2.84s	remaining: 47.9s
56:	total: 2.89s	remaining: 47.9s
57:	total: 2.94s	remaining: 47.7s
58:	total: 2.99s	remaining: 47.7s
59:	total: 3.04s	remaining: 47.6s
60:	total: 3.09s	remaining: 47.6s
61:	total: 3.13s	remaining: 47.4s
62:	total: 3.18s	remaining: 47.3s
63:	total: 3.23s	remaining: 47.3s
64:	total: 3.28s	remaining: 47.2s
65:	total: 3.34s	remaining: 47.2s
66:	total: 3.39s	remaining: 47.2s
67:	total: 3.44s	remaining: 47.2s
68:	total: 3.49s	remaining: 47.1s
69:	total: 3.54s	remaining: 47s
70:	total: 3.59s	remaining: 47s
71:	total: 3.64s	remaining: 46.9s
72:	total: 3.69s	remaining: 46.9s
73:	total: 3.74s	remaining: 46.8s
74:	total: 3.79s	remaining: 46.7s
75:	total: 3.83s	remaining: 46.6s
76:	total: 3.88s	remaining: 46.5s
77:	total: 3.93s	remaining: 46.5s
78:	total: 3.98s	remaining: 46.4s
79:	total: 4.03s	remaining: 46.4s
80:	total: 4.08s	remaining: 46.3s
81:	total: 4.14s	remaining: 46.3s
82:	total: 4.18s	remaining: 46.2s
83:	total: 4.24s	remaining: 46.2s
84:	total: 4.28s	remaining: 46.1s
85:	total: 4.33s	remaining: 46s
86:	total: 4.38s	remaining: 45.9s
87:	total: 4.43s	remaining: 45.9s
88:	total: 4.47s	remaining: 45.8s
89:	total: 4.52s	remaining: 45.7s
90:	total: 4.57s	remaining: 45.6s
91:	total: 4.61s	remaining: 45.5s
92:	total: 4.66s	remaining: 45.5s
93:	total: 4.71s	remaining: 45.4s
94:	total: 4.76s	remaining: 45.4s
95:	total: 4.81s	remaining: 45.3s
96:	total: 4.87s	remaining: 45.3s
97:	total: 4.92s	remaining: 45.3s
98:	total: 4.98s	remaining: 45.3s
99:	total: 5.02s	remaining: 45.2s
100:	total: 5.08s	remaining: 45.2s
101:	total: 5.12s	remaining: 45.1s
102:	total: 5.17s	remaining: 45s
103:	total: 5.21s	remaining: 44.9s
104:	total: 5.25s	remaining: 44.8s
105:	total: 5.31s	remaining: 44.8s
106:	total: 5.36s	remaining: 44.7s
107:	total: 5.41s	remaining: 44.7s
108:	total: 5.45s	remaining: 44.6s
109:	total: 5.51s	remaining: 44.6s
110:	total: 5.57s	remaining: 44.6s
111:	total: 5.61s	remaining: 44.5s
112:	total: 5.66s	remaining: 44.4s
113:	total: 5.71s	remaining: 44.4s
114:	total: 5.76s	remaining: 44.3s
115:	total: 5.81s	remaining: 44.3s
116:	total: 5.86s	remaining: 44.2s
117:	total: 5.91s	remaining: 44.2s
118:	total: 5.96s	remaining: 44.2s
119:	total: 6.01s	remaining: 44s
120:	total: 6.05s	remaining: 44s
121:	total: 6.11s	remaining: 44s
122:	total: 6.16s	remaining: 44s
123:	total: 6.22s	remaining: 43.9s
124:	total: 6.26s	remaining: 43.8s
125:	total: 6.32s	remaining: 43.8s
126:	total: 6.37s	remaining: 43.8s
127:	total: 6.43s	remaining: 43.8s
128:	total: 6.47s	remaining: 43.7s
129:	total: 6.53s	remaining: 43.7s
130:	total: 6.58s	remaining: 43.6s
131:	total: 6.62s	remaining: 43.5s
132:	total: 6.67s	remaining: 43.5s
133:	total: 6.73s	remaining: 43.5s
134:	total: 6.78s	remaining: 43.5s
135:	total: 6.83s	remaining: 43.4s
136:	total: 6.88s	remaining: 43.3s
137:	total: 6.93s	remaining: 43.3s
138:	total: 6.98s	remaining: 43.3s
139:	total: 7.03s	remaining: 43.2s
140:	total: 7.08s	remaining: 43.2s
141:	total: 7.14s	remaining: 43.1s
142:	total: 7.19s	remaining: 43.1s
143:	total: 7.24s	remaining: 43s
144:	total: 7.28s	remaining: 42.9s
145:	total: 7.33s	remaining: 42.9s
146:	total: 7.38s	remaining: 42.8s
147:	total: 7.42s	remaining: 42.7s
148:	total: 7.48s	remaining: 42.7s
149:	total: 7.53s	remaining: 42.7s
150:	total: 7.57s	remaining: 42.6s
151:	total: 7.62s	remaining: 42.5s
152:	total: 7.67s	remaining: 42.5s
153:	total: 7.71s	remaining: 42.4s
154:	total: 7.76s	remaining: 42.3s
155:	total: 7.81s	remaining: 42.2s
156:	total: 7.85s	remaining: 42.2s
157:	total: 7.89s	remaining: 42.1s
158:	total: 7.94s	remaining: 42s
159:	total: 7.99s	remaining: 41.9s
160:	total: 8.03s	remaining: 41.9s
161:	total: 8.08s	remaining: 41.8s
162:	total: 8.13s	remaining: 41.8s
163:	total: 8.18s	remaining: 41.7s
164:	total: 8.22s	remaining: 41.6s
165:	total: 8.28s	remaining: 41.6s
166:	total: 8.32s	remaining: 41.5s
167:	total: 8.37s	remaining: 41.5s
168:	total: 8.42s	remaining: 41.4s
169:	total: 8.47s	remaining: 41.3s
170:	total: 8.51s	remaining: 41.3s
171:	total: 8.56s	remaining: 41.2s
172:	total: 8.61s	remaining: 41.2s
173:	total: 8.66s	remaining: 41.1s
174:	total: 8.71s	remaining: 41s
175:	total: 8.75s	remaining: 41s
176:	total: 8.79s	remaining: 40.9s
177:	total: 8.84s	remaining: 40.8s
178:	total: 8.88s	remaining: 40.8s
179:	total: 8.93s	remaining: 40.7s
180:	total: 8.97s	remaining: 40.6s
181:	total: 9.02s	remaining: 40.5s
182:	total: 9.06s	remaining: 40.5s
183:	total: 9.11s	remaining: 40.4s
184:	total: 9.15s	remaining: 40.3s
185:	total: 9.2s	remaining: 40.3s
186:	total: 9.25s	remaining: 40.2s
187:	total: 9.3s	remaining: 40.2s
188:	total: 9.34s	remaining: 40.1s
189:	total: 9.38s	remaining: 40s
190:	total: 9.43s	remaining: 39.9s
191:	total: 9.47s	remaining: 39.8s
192:	total: 9.51s	remaining: 39.8s
193:	total: 9.55s	remaining: 39.7s
194:	total: 9.6s	remaining: 39.6s
195:	total: 9.64s	remaining: 39.5s
196:	total: 9.68s	remaining: 39.5s
197:	total: 9.72s	remaining: 39.4s
198:	total: 9.77s	remaining: 39.3s
199:	total: 9.81s	remaining: 39.2s
200:	total: 9.85s	remaining: 39.2s
201:	total: 9.9s	remaining: 39.1s
202:	total: 9.95s	remaining: 39.1s
203:	total: 9.99s	remaining: 39s
204:	total: 10s	remaining: 38.9s
205:	total: 10.1s	remaining: 38.8s
206:	total: 10.1s	remaining: 38.7s
207:	total: 10.2s	remaining: 38.7s
208:	total: 10.2s	remaining: 38.6s
209:	total: 10.3s	remaining: 38.6s
210:	total: 10.3s	remaining: 38.5s
211:	total: 10.3s	remaining: 38.4s
212:	total: 10.4s	remaining: 38.3s
213:	total: 10.4s	remaining: 38.3s
214:	total: 10.5s	remaining: 38.2s
215:	total: 10.5s	remaining: 38.1s
216:	total: 10.5s	remaining: 38.1s
217:	total: 10.6s	remaining: 38s
218:	total: 10.6s	remaining: 37.9s
219:	total: 10.7s	remaining: 37.9s
220:	total: 10.7s	remaining: 37.8s
221:	total: 10.8s	remaining: 37.8s
222:	total: 10.8s	remaining: 37.7s
223:	total: 10.9s	remaining: 37.6s
224:	total: 10.9s	remaining: 37.6s
225:	total: 11s	remaining: 37.5s
226:	total: 11s	remaining: 37.5s
227:	total: 11.1s	remaining: 37.4s
228:	total: 11.1s	remaining: 37.4s
229:	total: 11.2s	remaining: 37.4s
230:	total: 11.2s	remaining: 37.3s
231:	total: 11.3s	remaining: 37.3s
232:	total: 11.3s	remaining: 37.2s
233:	total: 11.3s	remaining: 37.1s
234:	total: 11.4s	remaining: 37.1s
235:	total: 11.4s	remaining: 37s
236:	total: 11.5s	remaining: 37s
237:	total: 11.5s	remaining: 36.9s
238:	total: 11.6s	remaining: 36.9s
239:	total: 11.6s	remaining: 36.8s
240:	total: 11.7s	remaining: 36.8s
241:	total: 11.7s	remaining: 36.7s
242:	total: 11.8s	remaining: 36.7s
243:	total: 11.8s	remaining: 36.6s
244:	total: 11.9s	remaining: 36.6s
245:	total: 11.9s	remaining: 36.5s
246:	total: 12s	remaining: 36.5s
247:	total: 12s	remaining: 36.4s
248:	total: 12.1s	remaining: 36.4s
249:	total: 12.1s	remaining: 36.3s
250:	total: 12.2s	remaining: 36.3s
251:	total: 12.2s	remaining: 36.2s
252:	total: 12.3s	remaining: 36.2s
253:	total: 12.3s	remaining: 36.1s
254:	total: 12.3s	remaining: 36.1s
255:	total: 12.4s	remaining: 36s
256:	total: 12.4s	remaining: 36s
257:	total: 12.5s	remaining: 35.9s
258:	total: 12.5s	remaining: 35.9s
259:	total: 12.6s	remaining: 35.8s
260:	total: 12.6s	remaining: 35.8s
261:	total: 12.7s	remaining: 35.7s
262:	total: 12.7s	remaining: 35.7s
263:	total: 12.8s	remaining: 35.7s
264:	total: 12.9s	remaining: 35.7s
265:	total: 12.9s	remaining: 35.6s
266:	total: 12.9s	remaining: 35.5s
267:	total: 13s	remaining: 35.5s
268:	total: 13s	remaining: 35.4s
269:	total: 13.1s	remaining: 35.4s
270:	total: 13.1s	remaining: 35.4s
271:	total: 13.2s	remaining: 35.3s
272:	total: 13.2s	remaining: 35.3s
273:	total: 13.3s	remaining: 35.2s
274:	total: 13.3s	remaining: 35.2s
275:	total: 13.4s	remaining: 35.1s
276:	total: 13.4s	remaining: 35.1s
277:	total: 13.5s	remaining: 35s
278:	total: 13.5s	remaining: 35s
279:	total: 13.6s	remaining: 34.9s
280:	total: 13.6s	remaining: 34.9s
281:	total: 13.7s	remaining: 34.8s
282:	total: 13.7s	remaining: 34.8s
283:	total: 13.8s	remaining: 34.7s
284:	total: 13.8s	remaining: 34.7s
285:	total: 13.9s	remaining: 34.6s
286:	total: 13.9s	remaining: 34.6s
287:	total: 14s	remaining: 34.5s
288:	total: 14s	remaining: 34.5s
289:	total: 14.1s	remaining: 34.4s
290:	total: 14.1s	remaining: 34.4s
291:	total: 14.2s	remaining: 34.3s
292:	total: 14.2s	remaining: 34.3s
293:	total: 14.3s	remaining: 34.2s
294:	total: 14.3s	remaining: 34.2s
295:	total: 14.4s	remaining: 34.1s
296:	total: 14.4s	remaining: 34.1s
297:	total: 14.4s	remaining: 34s
298:	total: 14.5s	remaining: 34s
299:	total: 14.5s	remaining: 33.9s
300:	total: 14.6s	remaining: 33.9s
301:	total: 14.6s	remaining: 33.8s
302:	total: 14.7s	remaining: 33.7s
303:	total: 14.7s	remaining: 33.7s
304:	total: 14.8s	remaining: 33.6s
305:	total: 14.8s	remaining: 33.6s
306:	total: 14.8s	remaining: 33.5s
307:	total: 14.9s	remaining: 33.4s
308:	total: 14.9s	remaining: 33.4s
309:	total: 15s	remaining: 33.3s
310:	total: 15s	remaining: 33.3s
311:	total: 15.1s	remaining: 33.2s
312:	total: 15.1s	remaining: 33.2s
313:	total: 15.1s	remaining: 33.1s
314:	total: 15.2s	remaining: 33.1s
315:	total: 15.2s	remaining: 33s
316:	total: 15.3s	remaining: 33s
317:	total: 15.3s	remaining: 32.9s
318:	total: 15.4s	remaining: 32.8s
319:	total: 15.4s	remaining: 32.8s
320:	total: 15.5s	remaining: 32.8s
321:	total: 15.5s	remaining: 32.7s
322:	total: 15.6s	remaining: 32.6s
323:	total: 15.6s	remaining: 32.6s
324:	total: 15.7s	remaining: 32.5s
325:	total: 15.7s	remaining: 32.5s
326:	total: 15.7s	remaining: 32.4s
327:	total: 15.8s	remaining: 32.3s
328:	total: 15.8s	remaining: 32.3s
329:	total: 15.9s	remaining: 32.3s
330:	total: 15.9s	remaining: 32.2s
331:	total: 16s	remaining: 32.2s
332:	total: 16s	remaining: 32.1s
333:	total: 16.1s	remaining: 32.1s
334:	total: 16.1s	remaining: 32s
335:	total: 16.2s	remaining: 32s
336:	total: 16.2s	remaining: 31.9s
337:	total: 16.3s	remaining: 31.9s
338:	total: 16.3s	remaining: 31.8s
339:	total: 16.4s	remaining: 31.8s
340:	total: 16.4s	remaining: 31.7s
341:	total: 16.4s	remaining: 31.6s
342:	total: 16.5s	remaining: 31.6s
343:	total: 16.5s	remaining: 31.5s
344:	total: 16.6s	remaining: 31.5s
345:	total: 16.6s	remaining: 31.4s
346:	total: 16.7s	remaining: 31.4s
347:	total: 16.7s	remaining: 31.3s
348:	total: 16.8s	remaining: 31.3s
349:	total: 16.8s	remaining: 31.2s
350:	total: 16.9s	remaining: 31.2s
351:	total: 16.9s	remaining: 31.1s
352:	total: 16.9s	remaining: 31.1s
353:	total: 17s	remaining: 31s
354:	total: 17s	remaining: 31s
355:	total: 17.1s	remaining: 30.9s
356:	total: 17.1s	remaining: 30.9s
357:	total: 17.2s	remaining: 30.8s
358:	total: 17.2s	remaining: 30.8s
359:	total: 17.3s	remaining: 30.7s
360:	total: 17.3s	remaining: 30.7s
361:	total: 17.4s	remaining: 30.6s
362:	total: 17.4s	remaining: 30.6s
363:	total: 17.5s	remaining: 30.6s
364:	total: 17.5s	remaining: 30.5s
365:	total: 17.6s	remaining: 30.5s
366:	total: 17.6s	remaining: 30.4s
367:	total: 17.7s	remaining: 30.4s
368:	total: 17.7s	remaining: 30.3s
369:	total: 17.8s	remaining: 30.3s
370:	total: 17.8s	remaining: 30.3s
371:	total: 17.9s	remaining: 30.2s
372:	total: 17.9s	remaining: 30.2s
373:	total: 18s	remaining: 30.1s
374:	total: 18s	remaining: 30.1s
375:	total: 18.1s	remaining: 30s
376:	total: 18.1s	remaining: 30s
377:	total: 18.2s	remaining: 29.9s
378:	total: 18.2s	remaining: 29.9s
379:	total: 18.3s	remaining: 29.8s
380:	total: 18.3s	remaining: 29.8s
381:	total: 18.4s	remaining: 29.7s
382:	total: 18.4s	remaining: 29.7s
383:	total: 18.5s	remaining: 29.6s
384:	total: 18.5s	remaining: 29.6s
385:	total: 18.6s	remaining: 29.5s
386:	total: 18.6s	remaining: 29.5s
387:	total: 18.6s	remaining: 29.4s
388:	total: 18.7s	remaining: 29.4s
389:	total: 18.7s	remaining: 29.3s
390:	total: 18.8s	remaining: 29.3s
391:	total: 18.8s	remaining: 29.2s
392:	total: 18.9s	remaining: 29.2s
393:	total: 18.9s	remaining: 29.1s
394:	total: 19s	remaining: 29.1s
395:	total: 19s	remaining: 29s
396:	total: 19.1s	remaining: 29s
397:	total: 19.1s	remaining: 28.9s
398:	total: 19.2s	remaining: 28.9s
399:	total: 19.2s	remaining: 28.9s
400:	total: 19.3s	remaining: 28.8s
401:	total: 19.3s	remaining: 28.8s
402:	total: 19.4s	remaining: 28.7s
403:	total: 19.4s	remaining: 28.7s
404:	total: 19.5s	remaining: 28.6s
405:	total: 19.5s	remaining: 28.6s
406:	total: 19.6s	remaining: 28.5s
407:	total: 19.6s	remaining: 28.5s
408:	total: 19.7s	remaining: 28.4s
409:	total: 19.7s	remaining: 28.4s
410:	total: 19.8s	remaining: 28.3s
411:	total: 19.8s	remaining: 28.3s
412:	total: 19.9s	remaining: 28.2s
413:	total: 19.9s	remaining: 28.2s
414:	total: 19.9s	remaining: 28.1s
415:	total: 20s	remaining: 28.1s
416:	total: 20s	remaining: 28s
417:	total: 20.1s	remaining: 27.9s
418:	total: 20.1s	remaining: 27.9s
419:	total: 20.2s	remaining: 27.8s
420:	total: 20.2s	remaining: 27.8s
421:	total: 20.3s	remaining: 27.7s
422:	total: 20.3s	remaining: 27.7s
423:	total: 20.3s	remaining: 27.6s
424:	total: 20.4s	remaining: 27.6s
425:	total: 20.4s	remaining: 27.5s
426:	total: 20.5s	remaining: 27.5s
427:	total: 20.5s	remaining: 27.4s
428:	total: 20.6s	remaining: 27.4s
429:	total: 20.6s	remaining: 27.3s
430:	total: 20.6s	remaining: 27.3s
431:	total: 20.7s	remaining: 27.2s
432:	total: 20.7s	remaining: 27.2s
433:	total: 20.8s	remaining: 27.1s
434:	total: 20.8s	remaining: 27s
435:	total: 20.9s	remaining: 27s
436:	total: 20.9s	remaining: 26.9s
437:	total: 21s	remaining: 26.9s
438:	total: 21s	remaining: 26.9s
439:	total: 21.1s	remaining: 26.8s
440:	total: 21.1s	remaining: 26.8s
441:	total: 21.2s	remaining: 26.7s
442:	total: 21.2s	remaining: 26.7s
443:	total: 21.3s	remaining: 26.6s
444:	total: 21.3s	remaining: 26.6s
445:	total: 21.4s	remaining: 26.6s
446:	total: 21.4s	remaining: 26.5s
447:	total: 21.5s	remaining: 26.5s
448:	total: 21.5s	remaining: 26.4s
449:	total: 21.6s	remaining: 26.4s
450:	total: 21.6s	remaining: 26.3s
451:	total: 21.7s	remaining: 26.3s
452:	total: 21.7s	remaining: 26.3s
453:	total: 21.8s	remaining: 26.2s
454:	total: 21.9s	remaining: 26.2s
455:	total: 21.9s	remaining: 26.1s
456:	total: 22s	remaining: 26.1s
457:	total: 22s	remaining: 26.1s
458:	total: 22.1s	remaining: 26s
459:	total: 22.1s	remaining: 26s
460:	total: 22.2s	remaining: 25.9s
461:	total: 22.2s	remaining: 25.9s
462:	total: 22.3s	remaining: 25.8s
463:	total: 22.3s	remaining: 25.8s
464:	total: 22.4s	remaining: 25.8s
465:	total: 22.4s	remaining: 25.7s
466:	total: 22.5s	remaining: 25.7s
467:	total: 22.5s	remaining: 25.6s
468:	total: 22.6s	remaining: 25.6s
469:	total: 22.6s	remaining: 25.5s
470:	total: 22.7s	remaining: 25.5s
471:	total: 22.7s	remaining: 25.4s
472:	total: 22.8s	remaining: 25.4s
473:	total: 22.8s	remaining: 25.3s
474:	total: 22.9s	remaining: 25.3s
475:	total: 22.9s	remaining: 25.2s
476:	total: 23s	remaining: 25.2s
477:	total: 23s	remaining: 25.2s
478:	total: 23.1s	remaining: 25.1s
479:	total: 23.1s	remaining: 25.1s
480:	total: 23.2s	remaining: 25s
481:	total: 23.2s	remaining: 25s
482:	total: 23.3s	remaining: 24.9s
483:	total: 23.3s	remaining: 24.9s
484:	total: 23.4s	remaining: 24.8s
485:	total: 23.4s	remaining: 24.8s
486:	total: 23.5s	remaining: 24.8s
487:	total: 23.5s	remaining: 24.7s
488:	total: 23.6s	remaining: 24.7s
489:	total: 23.6s	remaining: 24.6s
490:	total: 23.7s	remaining: 24.6s
491:	total: 23.7s	remaining: 24.5s
492:	total: 23.8s	remaining: 24.5s
493:	total: 23.8s	remaining: 24.4s
494:	total: 23.9s	remaining: 24.4s
495:	total: 23.9s	remaining: 24.3s
496:	total: 24s	remaining: 24.3s
497:	total: 24.1s	remaining: 24.2s
498:	total: 24.1s	remaining: 24.2s
499:	total: 24.2s	remaining: 24.2s
500:	total: 24.2s	remaining: 24.1s
501:	total: 24.3s	remaining: 24.1s
502:	total: 24.3s	remaining: 24s
503:	total: 24.4s	remaining: 24s
504:	total: 24.4s	remaining: 23.9s
505:	total: 24.5s	remaining: 23.9s
506:	total: 24.5s	remaining: 23.8s
507:	total: 24.6s	remaining: 23.8s
508:	total: 24.6s	remaining: 23.7s
509:	total: 24.6s	remaining: 23.7s
510:	total: 24.7s	remaining: 23.6s
511:	total: 24.7s	remaining: 23.6s
512:	total: 24.8s	remaining: 23.5s
513:	total: 24.8s	remaining: 23.5s
514:	total: 24.9s	remaining: 23.4s
515:	total: 24.9s	remaining: 23.4s
516:	total: 25s	remaining: 23.3s
517:	total: 25s	remaining: 23.3s
518:	total: 25.1s	remaining: 23.2s
519:	total: 25.1s	remaining: 23.2s
520:	total: 25.1s	remaining: 23.1s
521:	total: 25.2s	remaining: 23.1s
522:	total: 25.2s	remaining: 23s
523:	total: 25.3s	remaining: 23s
524:	total: 25.3s	remaining: 22.9s
525:	total: 25.4s	remaining: 22.9s
526:	total: 25.4s	remaining: 22.8s
527:	total: 25.5s	remaining: 22.8s
528:	total: 25.5s	remaining: 22.7s
529:	total: 25.5s	remaining: 22.6s
530:	total: 25.6s	remaining: 22.6s
531:	total: 25.6s	remaining: 22.5s
532:	total: 25.7s	remaining: 22.5s
533:	total: 25.7s	remaining: 22.5s
534:	total: 25.8s	remaining: 22.4s
535:	total: 25.8s	remaining: 22.4s
536:	total: 25.9s	remaining: 22.3s
537:	total: 25.9s	remaining: 22.3s
538:	total: 26s	remaining: 22.2s
539:	total: 26s	remaining: 22.2s
540:	total: 26.1s	remaining: 22.1s
541:	total: 26.1s	remaining: 22.1s
542:	total: 26.1s	remaining: 22s
543:	total: 26.2s	remaining: 22s
544:	total: 26.2s	remaining: 21.9s
545:	total: 26.3s	remaining: 21.9s
546:	total: 26.3s	remaining: 21.8s
547:	total: 26.4s	remaining: 21.8s
548:	total: 26.4s	remaining: 21.7s
549:	total: 26.5s	remaining: 21.7s
550:	total: 26.5s	remaining: 21.6s
551:	total: 26.6s	remaining: 21.6s
552:	total: 26.6s	remaining: 21.5s
553:	total: 26.6s	remaining: 21.5s
554:	total: 26.7s	remaining: 21.4s
555:	total: 26.7s	remaining: 21.4s
556:	total: 26.8s	remaining: 21.3s
557:	total: 26.8s	remaining: 21.3s
558:	total: 26.9s	remaining: 21.2s
559:	total: 26.9s	remaining: 21.2s
560:	total: 27s	remaining: 21.1s
561:	total: 27s	remaining: 21.1s
562:	total: 27.1s	remaining: 21s
563:	total: 27.1s	remaining: 20.9s
564:	total: 27.1s	remaining: 20.9s
565:	total: 27.2s	remaining: 20.8s
566:	total: 27.2s	remaining: 20.8s
567:	total: 27.3s	remaining: 20.7s
568:	total: 27.3s	remaining: 20.7s
569:	total: 27.4s	remaining: 20.6s
570:	total: 27.4s	remaining: 20.6s
571:	total: 27.4s	remaining: 20.5s
572:	total: 27.5s	remaining: 20.5s
573:	total: 27.5s	remaining: 20.4s
574:	total: 27.6s	remaining: 20.4s
575:	total: 27.6s	remaining: 20.3s
576:	total: 27.7s	remaining: 20.3s
577:	total: 27.7s	remaining: 20.2s
578:	total: 27.8s	remaining: 20.2s

CatBoostError: C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/libs/data/model_dataset_compatibility.cpp:53: Feature title is Categorical in model but marked different in the dataset